/*
  This file is automatically generated. Any changes will be overwritten.
  Modify add-aa-kunden-kontakte.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { NumericComponent } from '@radzen/angular/dist/numeric';
import { CheckBoxComponent } from '@radzen/angular/dist/checkbox';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';

import { DbSinDarElaService } from '../db-sin-dar-ela.service';
import { SecurityService } from '../security.service';

export class AddAaKundenKontakteGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('form0') form0: TemplateFormComponent;
  @ViewChild('kundenIdLabel') kundenIdLabel: LabelComponent;
  @ViewChild('kundenId') kundenId: DropDownComponent;
  @ViewChild('kundenIdRequiredValidator') kundenIdRequiredValidator: RequiredValidatorComponent;
  @ViewChild('kundenKontaktArtIdLabel') kundenKontaktArtIdLabel: LabelComponent;
  @ViewChild('kundenKontaktArtId') kundenKontaktArtId: DropDownComponent;
  @ViewChild('kundenKontaktArtIdRequiredValidator') kundenKontaktArtIdRequiredValidator: RequiredValidatorComponent;
  @ViewChild('nameLabel') nameLabel: LabelComponent;
  @ViewChild('name') name: TextBoxComponent;
  @ViewChild('nameRequiredValidator') nameRequiredValidator: RequiredValidatorComponent;
  @ViewChild('adresseLabel') adresseLabel: LabelComponent;
  @ViewChild('adresse') adresse: TextBoxComponent;
  @ViewChild('telefonLabel') telefonLabel: LabelComponent;
  @ViewChild('telefon') telefon: TextBoxComponent;
  @ViewChild('eMailLabel') eMailLabel: LabelComponent;
  @ViewChild('eMail') eMail: TextBoxComponent;
  @ViewChild('baseIdLabel') baseIdLabel: LabelComponent;
  @ViewChild('baseId') baseId: NumericComponent;
  @ViewChild('hauptansprechpartnerLabel') hauptansprechpartnerLabel: LabelComponent;
  @ViewChild('hauptansprechpartner') hauptansprechpartner: CheckBoxComponent;
  @ViewChild('infoLabel') infoLabel: LabelComponent;
  @ViewChild('info') info: TextBoxComponent;
  @ViewChild('button1') button1: ButtonComponent;
  @ViewChild('button2') button2: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbSinDarEla: DbSinDarElaService;

  security: SecurityService;
  getKundensResult: any;
  getKundenKontakteArtensResult: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbSinDarEla = this.injector.get(DbSinDarElaService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.dbSinDarEla.getKundens(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.getKundensResult = result.value;
    }, (result: any) => {

    });

    this.dbSinDarEla.getKundenKontakteArtens(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.getKundenKontakteArtensResult = result.value;
    }, (result: any) => {

    });
  }

  form0Submit(event: any) {
    this.dbSinDarEla.createKundenKontakte(null, event)
    .subscribe((result: any) => {
      if (this.dialogRef) {
        this.dialogRef.close();
      } else {
        this._location.back();
      }
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to create new KundenKontakte!` });
    });
  }

  button2Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }
}
