/*
  This file is automatically generated. Any changes will be overwritten.
  Modify kunden.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { DataListComponent } from '@radzen/angular/dist/datalist';
import { ImageComponent } from '@radzen/angular/dist/image';
import { LabelComponent } from '@radzen/angular/dist/label';
import { IconComponent } from '@radzen/angular/dist/icon';

import { ConfigService } from '../config.service';

import { DbSinDarElaService } from '../db-sin-dar-ela.service';
import { SecurityService } from '../security.service';

export class KundenGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('textboxSuchenKunden') textboxSuchenKunden: TextBoxComponent;
  @ViewChild('buttonSuchenLoeschen') buttonSuchenLoeschen: ButtonComponent;
  @ViewChild('buttonSuchenTastatur') buttonSuchenTastatur: ButtonComponent;
  @ViewChild('datalistKunden') datalistKunden: DataListComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('buttonNavigateToKundenDaten') buttonNavigateToKundenDaten: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbSinDarEla: DbSinDarElaService;

  security: SecurityService;
  globalBenutzerBaseID: any;
  onClickStartKundenDaten: any;
  parameters: any;
  rstKunden: any;
  rstKundenCount: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbSinDarEla = this.injector.get(DbSinDarElaService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.globalBenutzerBaseID = localStorage.getItem("globalBenutzerBaseID");;

    this.datalistKunden.load();

    this.onClickStartKundenDaten = (data) => {
    if (this.dialogRef) {
      this.dialogRef.close();
    }
    this.router.navigate(['kunden-daten', data.KundenID]);
};
  }

  buttonSuchenLoeschenClick(event: any) {
    this.textboxSuchenKunden.value = null;
this.datalistKunden.load();
  }

  datalistKundenLoadData(event: any) {
    this.dbSinDarEla.getVwKundenUndBetreuerAuswahls(`BetreuerBaseID eq ${this.globalBenutzerBaseID} AND (contains(tolower(Name1),tolower('${this.textboxSuchenKunden.value || ''}')) OR contains(tolower(Name2),tolower('${this.textboxSuchenKunden.value || ''}')))`, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.rstKunden = result.value;

      this.rstKundenCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;
    }, (result: any) => {

    });
  }

  buttonNavigateToKundenDatenClick(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    }
    this.router.navigate(['kunden-daten', 0]);
  }
}
