/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { APP_INITIALIZER } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { BodyModule } from '@radzen/angular/dist/body';
import { ContentContainerModule } from '@radzen/angular/dist/content-container';
import { HeaderModule } from '@radzen/angular/dist/header';
import { ButtonModule } from '@radzen/angular/dist/button';
import { LabelModule } from '@radzen/angular/dist/label';
import { LinkModule } from '@radzen/angular/dist/link';
import { CardModule } from '@radzen/angular/dist/card';
import { ImageModule } from '@radzen/angular/dist/image';
import { IconModule } from '@radzen/angular/dist/icon';
import { ContentModule } from '@radzen/angular/dist/content';
import { HeadingModule } from '@radzen/angular/dist/heading';
import { LoginModule } from '@radzen/angular/dist/login';
import { HtmlModule } from '@radzen/angular/dist/html';
import { ProgressBarModule } from '@radzen/angular/dist/progressbar';
import { GaugeModule } from '@radzen/angular/dist/gauge';
import { SparklineModule } from '@radzen/angular/dist/sparkline';
import { TabsModule } from '@radzen/angular/dist/tabs';
import { TextBoxModule } from '@radzen/angular/dist/textbox';
import { DataListModule } from '@radzen/angular/dist/datalist';
import { DatePickerModule } from '@radzen/angular/dist/datepicker';
import { SchedulerModule } from '@radzen/angular/dist/scheduler';
import { SharedModule } from '@radzen/angular/dist/shared';
import { NotificationModule } from '@radzen/angular/dist/notification';
import { DialogModule } from '@radzen/angular/dist/dialog';

import { ConfigService, configServiceFactory } from './config.service';
import { AppRoutes } from './app.routes';
import { AppComponent } from './app.component';
import { CacheInterceptor } from './cache.interceptor';
export { AppComponent } from './app.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { AbmeldenComponent } from './abmelden/abmelden.component';
import { LoginComponent } from './login/login.component';
import { UnauthorizedComponent } from './unauthorized/unauthorized.component';
import { ZzDashboard1Component } from './zz-dashboard-1/zz-dashboard-1.component';
import { ZzDashboard2Component } from './zz-dashboard-2/zz-dashboard-2.component';
import { ZzDashboard3Component } from './zz-dashboard-3/zz-dashboard-3.component';
import { InfosComponent } from './infos/infos.component';
import { KundenComponent } from './kunden/kunden.component';
import { KundenDatenComponent } from './kunden-daten/kunden-daten.component';
import { DetailsLayoutComponent } from './details-layout/details-layout.component';
import { LoginLayoutComponent } from './login-layout/login-layout.component';
import { MainLayoutComponent } from './main-layout/main-layout.component';
import { KundenDatenLayoutComponent } from './kunden-daten-layout/kunden-daten-layout.component';
import { InfosLayoutComponent } from './infos-layout/infos-layout.component';
import { KundenLayoutComponent } from './kunden-layout/kunden-layout.component';

import { DbSinDarElaService } from './db-sin-dar-ela.service';
import { SecurityService, UserService } from './security.service';
import { SecurityInterceptor } from './security.interceptor';
import { AuthGuard } from './auth.guard';

export const PageDeclarations = [
  DashboardComponent,
  AbmeldenComponent,
  LoginComponent,
  UnauthorizedComponent,
  ZzDashboard1Component,
  ZzDashboard2Component,
  ZzDashboard3Component,
  InfosComponent,
  KundenComponent,
  KundenDatenComponent,
];

export const LayoutDeclarations = [
  DetailsLayoutComponent,
  LoginLayoutComponent,
  MainLayoutComponent,
  KundenDatenLayoutComponent,
  InfosLayoutComponent,
  KundenLayoutComponent,
];

export const AppDeclarations = [
  ...PageDeclarations,
  ...LayoutDeclarations,
  AppComponent
];

export const AppProviders = [
  {
    provide: HTTP_INTERCEPTORS,
    useClass: CacheInterceptor,
    multi: true
  },
  DbSinDarElaService,
  UserService,
  SecurityService,
  {
    provide: HTTP_INTERCEPTORS,
    useClass: SecurityInterceptor,
    multi: true
  },
  AuthGuard,
  ConfigService,
  {
    provide: APP_INITIALIZER,
    useFactory: configServiceFactory,
    deps: [ConfigService],
    multi: true
  }
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpClientModule,
  BodyModule,
  ContentContainerModule,
  HeaderModule,
  ButtonModule,
  LabelModule,
  LinkModule,
  CardModule,
  ImageModule,
  IconModule,
  ContentModule,
  HeadingModule,
  LoginModule,
  HtmlModule,
  ProgressBarModule,
  GaugeModule,
  SparklineModule,
  TabsModule,
  TextBoxModule,
  DataListModule,
  DatePickerModule,
  SchedulerModule,
  SharedModule,
  NotificationModule,
  DialogModule,
  AppRoutes
];
