/*
  This file is automatically generated. Any changes will be overwritten.
  Modify kunden-daten-kontakte-nbl.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { SelectBarComponent } from '@radzen/angular/dist/selectbar';
import { TextAreaComponent } from '@radzen/angular/dist/textarea';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { ConfigService } from '../config.service';
import { MeldungLoeschenComponent } from '../meldung-loeschen/meldung-loeschen.component';

import { DbSinDarElaService } from '../db-sin-dar-ela.service';
import { SecurityService } from '../security.service';

export class KundenDatenKontakteNblGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('form0') form0: TemplateFormComponent;
  @ViewChild('kundenKontaktArtIdLabel') kundenKontaktArtIdLabel: LabelComponent;
  @ViewChild('kundenKontaktArtId') kundenKontaktArtId: DropDownComponent;
  @ViewChild('kundenKontaktArtIdRequiredValidator') kundenKontaktArtIdRequiredValidator: RequiredValidatorComponent;
  @ViewChild('nameLabel') nameLabel: LabelComponent;
  @ViewChild('name') name: TextBoxComponent;
  @ViewChild('nameRequiredValidator') nameRequiredValidator: RequiredValidatorComponent;
  @ViewChild('adresseLabel') adresseLabel: LabelComponent;
  @ViewChild('adresse') adresse: TextBoxComponent;
  @ViewChild('telefonLabel') telefonLabel: LabelComponent;
  @ViewChild('telefon') telefon: TextBoxComponent;
  @ViewChild('eMailLabel') eMailLabel: LabelComponent;
  @ViewChild('eMail') eMail: TextBoxComponent;
  @ViewChild('hauptansprechpartnerLabel') hauptansprechpartnerLabel: LabelComponent;
  @ViewChild('hauptansprechpartner') hauptansprechpartner: SelectBarComponent;
  @ViewChild('requiredValidator0') requiredValidator0: RequiredValidatorComponent;
  @ViewChild('infoLabel') infoLabel: LabelComponent;
  @ViewChild('info') info: TextAreaComponent;
  @ViewChild('buttonLoeschen') buttonLoeschen: ButtonComponent;
  @ViewChild('buttonSpeichern') buttonSpeichern: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbSinDarEla: DbSinDarElaService;

  security: SecurityService;
  dsoKundenKontakt: any;
  rstKundenKontakteArten: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbSinDarEla = this.injector.get(DbSinDarElaService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    if (this.parameters.strModus == 'Neu') {
        this.dsoKundenKontakt = {};
    }

    if (this.parameters.strModus == 'Bearbeiten') {
          this.dbSinDarEla.getKundenKontakteByKundenKontaktId(null, this.parameters.intID)
      .subscribe((result: any) => {
          this.dsoKundenKontakt = result;
      }, (result: any) => {
    
      });
    }

    this.dbSinDarEla.getKundenKontakteArtens(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.rstKundenKontakteArten = result.value;
    }, (result: any) => {

    });
  }

  form0Submit(event: any) {
    if (this.parameters.strModus == 'Bearbeiten') {
          this.dbSinDarEla.updateKundenKontakte(null, this.parameters.intID, event)
      .subscribe((result: any) => {
          this.notificationService.notify({ severity: "success", summary: ``, detail: `Kontakt gespeichert` });

      this.dialogRef.close(result);
      }, (result: any) => {
          this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Kontakt konnte nicht gespeichert werden!` });
      });
    }

    if (this.parameters.strModus == 'Neu') {
          this.dbSinDarEla.createKundenKontakte(null, Object.assign(event, { KundenID: this.parameters.intID }))
      .subscribe((result: any) => {
          this.notificationService.notify({ severity: "success", summary: ``, detail: `Kontakt erstellt` });

      this.dialogRef.close(result);
      }, (result: any) => {
          this.notificationService.notify({ severity: "error", summary: ``, detail: `Kontakt konnte nicht erstellt werden!` });
      });
    }
  }

  buttonLoeschenClick(event: any) {
    this.dialogService.open(MeldungLoeschenComponent, { parameters: {strMeldung: "Soll der Kontakt '" + this.dsoKundenKontakt.Name + "' gelöscht werden?"}, title: `Löschen Kontakt` })
        .afterClosed().subscribe(result => {
              if (result == 'Löschen') {
              this.dbSinDarEla.deleteKundenKontakte(this.parameters.intID)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Kontakt gelöscht` });

        this.dialogRef.close(result);
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Kontakt konnte nicht gelöscht werden!` });
        });
      }
    });
  }
}
